### ISSUE TITLE
fail to build plug using fluidsynth on windows target

### ISSUE THREAD

**Issue by brummer10** [DISTRHO/dpf-makefile-action#1]
Hi, I try to use dpf-makefile-action to build Fluida.lv2 for Linux and windows.
While it works for Linux it fails for windows at building fluidsynth stated glibc and gthread was not found. 
Following the logs they was build successful.
This is what I get for windows build: https://github.com/brummer10/Fluida.lv2/actions/runs/7474496621/job/20340767708

and this is my workflow file: https://github.com/brummer10/Fluida.lv2/blob/master/.github/workflows/build.yml

do you've any hint for me what I doing wrong?

btw. using local PawPawBuilds works fine for building the windows version.

**Comment by falkTX** [comment]
there must be some bad logic on the pawpaw scripts where it only checks for the presence of the 0/1 values instead of checking its value.
fluidsynth is attempted to be built, but glib is skipped somehow.

**Comment by falkTX** [comment]
found it, a silly typo. https://github.com/DISTRHO/PawPaw/commit/34e00433dd358bb01437308bebc64ad9a490647f
just do a rebuild

**Comment by brummer10** [comment]
Thanks a lot. I can confirmed that it works now.
